# Travis CI configuration

language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev $PREFER_LOWEST

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/clover.xml
